//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectECS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public int EmpDesignation { get; set; }
        public int EmpService { get; set; }
        public string EmpPwd { get; set; }
        public string EmpImg { get; set; }
        public int EmpStatus { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Service Service { get; set; }
    }
}
