//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectECS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;

     
    public partial class Employee
    {
        public int EmpID { get; set; }

        [Required]
        [StringLength(50)]
        public string EmpName { get; set; }

        [Required]
        [EmailAddress]
        public string EmpEmail { get; set; }

        [Required]
        public int EmpDesignation { get; set; }

        [Required]
        public int EmpService { get; set; }

        [Required] 
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W).{8,}$", ErrorMessage = "Password must contain at least one uppercase letter, one lowercase letter, one digit, one special character, and have a minimum length of 8 characters.")]
        public string EmpPwd { get; set; }

        [Required(ErrorMessage = "Employee image is required.")] 
        public string EmpImg { get; set; }
        public int EmpStatus { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Service Service { get; set; }
    }
}
