//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectECS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int PaymentFor { get; set; }
        public int TotalAmount { get; set; }
        public string Status { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual PreferredService PreferredService { get; set; }
    }
}
